"""
csi_detector.py
---------------
Asmi's Module 1 — Culture-Specific Item (CSI) Detection

Detects items in source text that are culturally specific and cannot be
translated literally without losing meaning or causing confusion.

DATASET SOURCE:
  Term lists are loaded from data/csi_terms.json, which is generated by
  running: python3 data/build_csi_lists.py

  build_csi_lists.py downloads FLORES-200 (Meta's multilingual benchmark,
  1,012 English sentences) and uses Gemini to extract CSI terms from the
  corpus, then merges with a curated seed list.

  Citation: "We built our CSI lexicon by running our detector on the
  FLORES-200 English devtest corpus (Costa-jussà et al., 2022), identifying
  culture-specific items across four categories following Hershcovich et al.
  (2022)."

Two-tier detection:
  Tier 1: Fast lookup against terms from csi_terms.json (always runs)
  Tier 2: LLM-based detection for subtle cases not in the term list
          (runs when GEMINI_API_KEY is set)
"""

import re
import os
import json
import logging
from typing import List, Optional, Tuple, Dict

from pipeline.interfaces import PipelineInput, CSISpan

logger = logging.getLogger(__name__)

# Path to the dataset-generated term file
_TERMS_PATH = os.path.join(
    os.path.dirname(__file__), "..", "data", "csi_terms.json"
)

# Module-level cache so we only read from disk once
_terms_cache: Optional[Dict[str, List[str]]] = None

# Pragmatic patterns — kept as regex, not simple strings
_PRAGMATIC_PATTERNS = [
    r"\byours (sincerely|faithfully|truly|respectfully)\b",
    r"\bkind(est)? regards\b",
    r"\bbest regards\b",
    r"\bwarm(est)? regards\b",
    r"\bwith (kind|warm|best) regards\b",
    r"\blooking forward to hearing from you\b",
    r"\bthink nothing of it\b",
    r"\bdon't mention it\b",
    r"\bmy pleasure\b",
    r"\bthe pleasure is (all )?mine\b",
    r"\bno worries\b",
    r"\bnot a problem\b",
    r"\bcheers\b",
    r"\bfair dinkum\b",
    r"\bhow do you do\b",
    r"\bhow are you doing\b",
    r"\bhave a nice day\b",
    r"\byou're welcome\b",
    r"\bmy bad\b",
    r"\bsayonara\b",
    r"\bkonnichiwa\b",
    r"\bsenpai\b",
    r"\bsensei\b",
]


def _load_terms() -> Dict[str, List[str]]:
    """
    Load CSI term lists from data/csi_terms.json.
    Generated by: python3 data/build_csi_lists.py

    Falls back to empty lists if file doesn't exist (shouldn't happen
    after build_csi_lists.py has been run).
    """
    global _terms_cache
    if _terms_cache is not None:
        return _terms_cache

    if os.path.exists(_TERMS_PATH):
        try:
            with open(_TERMS_PATH, encoding="utf-8") as f:
                _terms_cache = json.load(f)
            total = sum(len(v) for v in _terms_cache.values())
            logger.info(
                f"CSI terms loaded from {_TERMS_PATH}: "
                f"{total} terms across {len(_terms_cache)} categories"
            )
        except Exception as e:
            logger.error(f"Failed to load csi_terms.json: {e}")
            _terms_cache = {
                "culturally_embedded": [], "proper_name": [],
                "institutional": [], "pragmatic": [],
            }
    else:
        logger.warning(
            f"csi_terms.json not found at {_TERMS_PATH}. "
            "Run: python3 data/build_csi_lists.py"
        )
        _terms_cache = {
            "culturally_embedded": [], "proper_name": [],
            "institutional": [], "pragmatic": [],
        }

    return _terms_cache


def _find_phrase(text: str, phrase: str) -> Optional[Tuple[int, int]]:
    """
    Return (start, end) character offsets of phrase in text (case-insensitive).
    Uses word-boundary matching to avoid partial matches.
    """
    escaped = re.escape(phrase)
    pattern = r"(?<!\w)" + escaped + r"(?!\w)"
    match = re.search(pattern, text, re.IGNORECASE)
    if match:
        return match.start(), match.end()
    return None


def _rule_based_csi(text: str) -> List[CSISpan]:
    """
    Detect CSIs using the dataset-generated term list from csi_terms.json.
    Fast, always runs, no API needed.
    """
    terms = _load_terms()
    spans: List[CSISpan] = []
    seen: set = set()

    def add(start: int, end: int, category: str, explanation: str):
        key = (start, end)
        if key not in seen:
            seen.add(key)
            spans.append({
                "span":        text[start:end],
                "start":       start,
                "end":         end,
                "category":    category,
                "explanation": explanation,
            })

    # Culturally embedded (idioms, proverbs, untranslatable concepts, humour)
    for term in terms.get("culturally_embedded", []):
        result = _find_phrase(text, term)
        if result:
            s, e = result
            add(s, e, "culturally_embedded",
                f'"{term}" is culturally embedded with no direct equivalent '
                "in most languages. Requires cultural adaptation.")

    # Proper names (foods, holidays, media, sports, places)
    for term in terms.get("proper_name", []):
        result = _find_phrase(text, term)
        if result:
            s, e = result
            add(s, e, "proper_name",
                f'"{term}" is a culturally specific reference '
                "(food, holiday, event, or institution) that carries "
                "meaning beyond its literal definition.")

    # Institutional terms (business, legal, financial abbreviations)
    text_lower = text.lower()
    for term in terms.get("institutional", []):
        pattern = r"\b" + re.escape(term) + r"\b"
        match = re.search(pattern, text_lower)
        if match:
            s, e = match.start(), match.end()
            add(s, e, "institutional",
                f'"{term}" is an institutional or domain-specific term '
                "that may not have a direct equivalent in the target culture.")

    # Pragmatic patterns (kept as regex — not simple strings)
    for pattern in _PRAGMATIC_PATTERNS:
        match = re.search(pattern, text, re.IGNORECASE)
        if match:
            s, e = match.start(), match.end()
            add(s, e, "pragmatic",
                f'"{match.group()}" is a pragmatic convention whose '
                "direct translation may sound unnatural in the target culture.")

    spans.sort(key=lambda sp: sp["start"])
    return spans


def _llm_based_csi(text: str, target_lang: str) -> List[CSISpan]:
    """
    Ask Gemini to find CSI items not in the term list.
    New LLM-discovered terms can later be added to csi_terms.json
    by re-running build_csi_lists.py.
    """
    from dotenv import load_dotenv
    load_dotenv()

    prompt = (
        f'You are a cultural linguistics expert. Find ALL culture-specific '
        f'items (CSIs) in this English text that would be challenging to '
        f'translate into language code "{target_lang}".\n\n'
        f'Text: "{text}"\n\n'
        f'Look for:\n'
        f'- Culturally specific foods (mochi, kimchi, haggis, grits...)\n'
        f'- Idioms and proverbs that do not translate literally\n'
        f'- Cultural concepts (karma, hygge, wabi-sabi, face-saving...)\n'
        f'- Superstitions and beliefs (knock on wood, evil eye...)\n'
        f'- Direct commands that are inappropriate in high-context cultures\n'
        f'- Humour, wordplay, puns, or jokes that are language-specific\n'
        f'- Holidays, festivals, and cultural events\n'
        f'- Media and popular culture references\n'
        f'- Institutions or systems specific to one country\n\n'
        f'Return a JSON array. Each element:\n'
        f'  span: exact text\n'
        f'  start: character index (0-based)\n'
        f'  end: character index where span ends\n'
        f'  category: "proper_name", "culturally_embedded", '
        f'"institutional", or "pragmatic"\n'
        f'  explanation: one sentence why it needs cultural adaptation\n'
        f'  confidence: float 0-1 (how certain you are this is a CSI)\n\n'
        f'Only include genuine CSIs with confidence >= 0.7. '
        f'Do NOT flag individual universal words: time words (tomorrow, today, soon, now), '
        f'basic verbs (do, make, take, go), basic emotions, numbers, or common objects. '
        f'DO flag: idioms, proverbs, direct commands inappropriate in high-context cultures, '
        f'culturally-loaded phrases, and expressions with no equivalent in the target language. '
        f'ONLY flag items that are genuinely untranslatable or culturally specific. '
        f'If none, return []. Return ONLY the JSON array.'
    )

    raw = None

    # Try Groq first
    groq_key = os.getenv("GROQ_API_KEY")
    if groq_key:
        try:
            from groq import Groq
            client = Groq(api_key=groq_key)
            resp = client.chat.completions.create(
                model="llama-3.3-70b-versatile",
                max_tokens=512,
                temperature=0.1,
                response_format={"type": "json_object"},
                messages=[
                    {"role": "system", "content": "You are a cultural linguistics expert. Always respond with a JSON object containing a 'csi_items' array."},
                    {"role": "user", "content": prompt + "\n\nRespond as: {\"csi_items\": [...array...]}"}
                ],
            )
            data = json.loads(resp.choices[0].message.content)
            items = data.get("csi_items", data) if isinstance(data, dict) else data
            raw = json.dumps(items) if isinstance(items, list) else "[]"
        except Exception as e:
            logger.debug(f"Groq CSI detection failed: {e}")

    # Try Gemini as fallback
    if raw is None:
        api_key = os.getenv("GEMINI_API_KEY")
        if api_key:
            try:
                import google.generativeai as genai
                genai.configure(api_key=api_key)
                model = genai.GenerativeModel(
                    "gemini-1.5-flash",
                    generation_config=genai.GenerationConfig(
                        response_mime_type="application/json",
                        temperature=0.1,
                    ),
                )
                response = model.generate_content(prompt)
                raw = response.text.strip()
            except Exception as e:
                logger.debug(f"Gemini CSI detection failed: {e}")

    if raw is None:
        return []

    try:

        if raw.startswith("["):
            items = json.loads(raw)
        else:
            match = re.search(r"\[[\s\S]*\]", raw)
            items = json.loads(match.group(0)) if match else []

        spans: List[CSISpan] = []
        for item in items:
            if all(k in item for k in ["span","start","end","category","explanation"]):
                # Filter low-confidence detections
                confidence = float(item.get("confidence", 1.0))
                if confidence < 0.7:
                    logger.debug(f"Skipping low-confidence CSI: {item['span']} ({confidence:.2f})")
                    continue
                spans.append({
                    "span":        item["span"],
                    "start":       int(item["start"]),
                    "end":         int(item["end"]),
                    "category":    item["category"],
                    "explanation": item["explanation"],
                })

        # Deduplicate by span text
        seen = set()
        unique_spans = []
        for s in spans:
            if s['span'] not in seen:
                seen.add(s['span'])
                unique_spans.append(s)
        spans = unique_spans

        if spans:
            logger.info(f"LLM CSI detection: {len(spans)} additional spans")

        return spans

    except Exception as e:
        logger.warning(f"LLM CSI detection failed (non-fatal): {e}")
        return []


def detect_csi_spans(pipeline_input: PipelineInput) -> List[CSISpan]:
    """
    Main entry point. Detect culture-specific items in source text.

    Term lists are loaded from data/csi_terms.json (built from FLORES-200).
    LLM tier runs additionally if GEMINI_API_KEY is set.

    Args:
        pipeline_input: PipelineInput from text_preprocessor

    Returns:
        List[CSISpan] — sorted by start position, deduplicated
    """
    text        = pipeline_input["text"]
    target_lang = pipeline_input["target_lang"]

    rule_spans = _rule_based_csi(text)
    llm_spans  = _llm_based_csi(text, target_lang)

    rule_ranges = {(s["start"], s["end"]) for s in rule_spans}
    rule_texts  = {s["span"].lower() for s in rule_spans}
    merged = rule_spans.copy()
    for span in llm_spans:
        key = (span["start"], span["end"])
        txt = span["span"].lower()
        if key not in rule_ranges and txt not in rule_texts:
            merged.append(span)
            rule_texts.add(txt)

    merged.sort(key=lambda s: s["start"])

    logger.info(
        f"CSI detection: {len(rule_spans)} rule-based + "
        f"{len(llm_spans)} LLM = {len(merged)} total"
    )
    return merged